export enum ItemReducerConstants {
  FETCH_ITEM_START = 'FETCH_ITEM_START',
  FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS',
  FETCH_ITEM_FAIL = 'FETCH_ITEM_FAIL',
  CREATE_ITEM_START = 'CREATE_ITEM_START',
  CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS',
  CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL',
  CLEAR_ITEM = 'CLEAR_ITEM',
  UPDATE_ITEM = 'UPDATE_ITEM',
  SET_ITEM = 'SET_ITEM',
  REPLACE_ITEM_IN_ITEM = 'REPLACE_ITEM_IN_ITEM',
}